name: "build_deploy_app"

on:
   push:
      branches:
         - master

jobs:
   app:
      name: "Build App"
      runs-on: ubuntu-latest
      steps:
         - name: "Build:checkout"
           uses: actions/checkout@v2
         - name: Push to GitHub Container Registry
            uses: docker/build-push-action@v2
            with:
               context: .
               push: true
               tags: ghcr.io/davidilie/kca-news
         # - name: Login to GitHub Container Registry
         #   uses: docker/login-action@v1
         #   with:
         #      registry: ghcr.io
         #      username: DavidIlie
         #      password: ${{ secrets.GHCR_PASSWORD }}
         # - name: Build and publish Docker image
         #   run: |
         #      docker build -t ghcr.io/davidilie/kca-news:latest .
         #      docker push ghcr.io/davidilie/kca-news:latest
   deploy_self:
      name: "Deploy"
      runs-on: ubuntu-latest
      needs: [app]
      steps:
         - name: "Set Kubernetes Context"
           uses: Azure/k8s-set-context@v1
           with:
              method: kubeconfig
              kubeconfig: ${{ secrets.KUBE_CONFIG }}
         - name: "Restart deployment"
           run: kubectl rollout restart deploy app -n kca-news
